admin:
    path: /
    defaults: { _controller: MiamBundle:Admin:index }

admin_feed_create:
    path: /feed/create
    defaults: { _controller: MiamBundle:Admin:createFeed }

ajax_admin_feed_parse:
    path: /ajax/feed/{id}/parse
    defaults: { _controller: MiamBundle:Admin:ajaxParseFeed }
    requirements: { id: \d+ }

ajax_admin_feed_delete:
    path: /ajax/feed/{id}/delete
    defaults: { _controller: MiamBundle:Admin:ajaxDeleteFeed }
    requirements: { id: \d+ }

admin_parse_all:
    path: /parse/all
    defaults: { _controller: MiamBundle:Admin:parseAll }
