admin:
    path: /
    defaults: { _controller: MiamBundle:Admin:index }

admin_feed_create:
    path: /feed/create
    defaults: { _controller: MiamBundle:Admin:createFeed }

ajax_admin_feed_parse:
    path: /ajax/feed/{id}/parse
    defaults: { _controller: MiamBundle:Admin:ajaxParseFeed }
    requirements: { id: \d+ }

ajax_admin_feed_delete:
    path: /ajax/feed/{id}/delete
    defaults: { _controller: MiamBundle:Admin:ajaxDeleteFeed }
    requirements: { id: \d+ }

admin_feeds_export:
    path: /feeds/export
    defaults: { _controller: MiamBundle:Admin:exportFeeds }

ajax_admin_popup_feeds_import:
    path: /ajax/popup/feeds/import
    defaults: { _controller: MiamBundle:Admin:ajaxPopupImportFeeds }

admin_feeds_import:
    path: /feeds/import
    defaults: { _controller: MiamBundle:Admin:importFeeds }
