catalog:
    path: /
    defaults: { _controller: MiamBundle:Catalog:index }

catalog_feeds:
    path: /feeds
    defaults: { _controller: MiamBundle:Catalog:showFeeds }

catalog_feed:
    path: /feed/{id}
    defaults: { _controller: MiamBundle:Catalog:showFeed }
    requirements: { id: \d+ }

catalog_items:
    path: /items
    defaults: { _controller: MiamBundle:Catalog:showItems }

ajax_catalog_feed_subscribe:
    path: /ajax/feed/{id}/subscribe
    defaults: { _controller: MiamBundle:Catalog:ajaxSubscribeToFeed }
    requirements: { id: \d+ }

ajax_catalog_feed_unsubscribe:
    path: /ajax/feed/{id}/unsubscribe
    defaults: { _controller: MiamBundle:Catalog:ajaxUnsubscribeFromFeed }
    requirements: { id: \d+ }

ajax_catalog_feed_get_items:
    path: /ajax/feed/{id}/items/{page}
    defaults: { _controller: MiamBundle:Catalog:ajaxGetItemsForFeed }
    requirements: { id: \d+, page: \d+ }