index:
    path: /
    defaults: { _controller: MiamBundle:Default:index }

miam_admin:
    resource: "@MiamBundle/Resources/config/routing/admin.yml"
    prefix: /admin

miam_catalog:
    resource: "@MiamBundle/Resources/config/routing/catalog.yml"
    prefix: /catalog

miam_manager:
    resource: "@MiamBundle/Resources/config/routing/manager.yml"
    prefix: /manager

miam_security:
    resource: "@MiamBundle/Resources/config/routing/security.yml"

miam_shit:
    resource: "@MiamBundle/Resources/config/routing/shit.yml"
    prefix: /shit

user:
    path: /user/{userId}
    defaults: { _controller: MiamBundle:Shit:index }
    requirements: { userId: \d+ }

pubsubhubbub:
    path: /pshb
    defaults: { _controller: MiamBundle:Default:pshb }

ajax_get_item:
    path: /ajax/item
    defaults: { _controller: MiamBundle:Default:ajaxGetItem }