index:
    path: /
    defaults: { _controller: MiamBundle:Default:index }

miam_admin:
    resource: "@MiamBundle/Resources/config/routing/admin.yml"
    prefix: /admin

miam_manager:
    resource: "@MiamBundle/Resources/config/routing/manager.yml"
    prefix: /manager

miam_security:
    resource: "@MiamBundle/Resources/config/routing/security.yml"

miam_shit:
    resource: "@MiamBundle/Resources/config/routing/shit.yml"
    prefix: /shit
