services:
    category_manager:
        class: MiamBundle\Services\CategoryManager
        arguments: ["@doctrine.orm.default_entity_manager", "@service_container"]
    data_parsing:
        class: MiamBundle\Services\DataParsing
        arguments: ["@doctrine.orm.default_entity_manager", "@service_container"]
    feed_manager:
        class: MiamBundle\Services\FeedManager
        arguments: ["@doctrine.orm.default_entity_manager", "@service_container"]
    locale_listener:
        class: MiamBundle\EventListener\LocaleListener
        arguments: ["%kernel.default_locale%"]
        tags:
            - { name: kernel.event_subscriber }
    mark_manager:
        class: MiamBundle\Services\MarkManager
        arguments: ["@doctrine.orm.default_entity_manager"]
    pubsubhubbub:
        class: MiamBundle\Services\PubSubHubBub
        arguments: ["@doctrine.orm.default_entity_manager", "@service_container"]
    text_extension:
        class: MiamBundle\Twig\TextExtension
        public: false
        tags:
            - { name: twig.extension }
    user_locale_listener:
        class: MiamBundle\EventListener\UserLocaleListener
        arguments: ["@session"]
        tags:
            - { name: kernel.event_listener, event: security.interactive_login, method: onInteractiveLogin }