MiamBundle\Entity\Category:
    type: entity
    table: category
    repositoryClass: MiamBundle\Repository\CategoryRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
        dateCreated:
            type: datetime
            column: date_created
        leftPosition:
            type: integer
            column: left_position
            nullable: true
        rightPosition:
            type: integer
            column: right_position
            nullable: true
        level:
            type: integer
            column: level
    manyToOne:
        parent:
            targetEntity: Category
            inversedBy: subcategories
            joinColumn:
                name: parent_id
                referencedColumnName: id
                nullable: true
        user:
            targetEntity: User
            inversedBy: categories
            joinColumn:
                name: user_id
                referencedColumnName: id
    oneToMany:
        subcategories:
            targetEntity: Category
            mappedBy: parent
            cascade: ["remove"]
        subscriptions:
            targetEntity: Subscription
            mappedBy: category
    lifecycleCallbacks: {  }
