MiamBundle\Entity\Feed:
    type: entity
    table: feed
    repositoryClass: MiamBundle\Repository\FeedRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        originalName:
            type: string
            column: name_original
            length: 255
            nullable: true
        customName:
            type: string
            column: name_custom
            length: 255
            nullable: true
        originalDescription:
            type: text
            column: description_original
            nullable: true
        customDescription:
            type: text
            column: description_custom
            nullable: true
        url:
            type: text
        urlHash:
            type: string
            column: url_hash
            length: 40
        iconUrl:
            type: text
            column: icon_url
            nullable: true
        website:
            type: text
            nullable: true
        author:
            type: text
            nullable: true
        language:
            type: string
            length: 255
            nullable: true
        dataLength:
            type: integer
            column: data_length
        countFirstParsedItems:
            type: integer
            column: count_items_parsed_first
        countLastParsedItems:
            type: integer
            column: count_items_parsed_last
        countTotalItems:
            type: integer
            column: count_items_total
        countDailyItems:
            type: float
            column: count_items_daily
        errorCount:
            type: integer
            column: error_count
        errorMessage:
            type: text
            column: error_message
            nullable: true
        hasIcon:
            type: boolean
            column: has_icon
        dateCreated:
            type: datetime
            column: date_created
        dateParsed:
            type: datetime
            column: date_parsed
            nullable: true
        dateFirstSuccess:
            type: datetime
            column: date_success_first
            nullable: true
        dateLastSuccess:
            type: datetime
            column: date_success_last
            nullable: true
        dateNewItem:
            type: datetime
            column: date_new_item
            nullable: true
        dateIcon:
            type: datetime
            column: date_icon
            nullable: true
    oneToMany:
        items:
            targetEntity: Item
            mappedBy: feed
            cascade: ["remove"]
        subscriptions:
            targetEntity: Subscription
            mappedBy: feed
            cascade: ["remove"]
    uniqueConstraints:
        feed_url_hash_idx:
            columns: [ url_hash ]
    lifecycleCallbacks:
        preRemove: [ prepareIconRemoval ]
        postRemove: [ removeIcon ]