MiamBundle\Entity\Item:
    type: entity
    table: item
    repositoryClass: MiamBundle\Repository\ItemRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        title:
            type: string
            length: 255
            nullable: true
        link:
            type: text
            nullable: true
        identifier:
            type: string
            length: 255
        hashIdentifier:
            type: string
            length: 40
            column: identifier_hash
        hash:
            type: string
            length: 40
        htmlContent:
            type: text
            column: content_html
        textContent:
            type: text
            column: content_text
        author:
            type: text
            nullable: true
        contributor:
            type: text
            nullable: true
        dateCreated:
            type: datetime
            column: date_created
        datePublished:
            type: datetime
            column: date_published
        dateUpdated:
            type: datetime
            column: date_updated
        dateModified:
            type: datetime
            column: date_modified
        dateLastSeen:
            type: datetime
            column: date_last_seen
    manyToMany:
        tags:
            targetEntity: Tag
            inversedBy: items
            joinTable:
                name: items_tags
                joinColumns:
                    item_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    tag_id:
                        referencedColumnName: id
    manyToOne:
        feed:
            targetEntity: Feed
            inversedBy: items
            joinColumn:
                name: feed_id
                referencedColumnName: id
    oneToMany:
        enclosures:
            targetEntity: Enclosure
            mappedBy: item
            cascade: ["remove"]
        marks:
            targetEntity: ItemMark
            mappedBy: item
            cascade: ["remove"]
    uniqueConstraints:
        item_feed_identifier_idx:
            columns: [ feed_id, identifier ]
    lifecycleCallbacks: {  }
