MiamBundle\Entity\ItemMark:
    type: entity
    table: item_mark
    repositoryClass: MiamBundle\Repository\ItemMarkRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: IDENTITY
    fields:
        isRead:
            type: boolean
            nullable: true
        isStarred:
            type: boolean
        dateRead:
            type: datetime
            nullable: true
    manyToOne:
        item:
            targetEntity: Item
            inversedBy: marks
            joinColumn:
                name: item_id
                referencedColumnName: id
        user:
            targetEntity: User
            joinColumn:
                name: user_id
                referencedColumnName: id
    uniqueConstraints:
        itemmark_item_user_idx:
            columns: [ item_id, user_id ]
    lifecycleCallbacks: {  }
