MiamBundle\Entity\PshbSubscription:
    type: entity
    table: pshb_subscription
    repositoryClass: MiamBundle\Repository\PshbSubscriptionRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        leaseSeconds:
            type: integer
            column: lease_seconds
        reason:
            type: text
            nullable: true
        dateCreated:
            type: datetime
            column: date_created
        dateSubscribed:
            type: datetime
            column: date_subscribed
            nullable: true
        dateUnsubscribed:
            type: datetime
            column: date_unsubscribed
            nullable: true
        dateDenied:
            type: datetime
            column: date_denied
            nullable: true
    manyToOne:
        feed:
            targetEntity: Feed
            inversedBy: pshbSubscriptions
            joinColumn:
                name: feed_id
                referencedColumnName: id
    lifecycleCallbacks: {  }
