MiamBundle\Entity\Subscription:
    type: entity
    table: subscription
    repositoryClass: MiamBundle\Repository\SubscriptionRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
            nullable: true
        dateCreated:
            type: datetime
            column: date_created
    manyToOne:
        category:
            targetEntity: Category
            inversedBy: subscriptions
            joinColumn:
                name: category_id
                referencedColumnName: id
                nullable: true
                onDelete: "SET NULL"
        feed:
            targetEntity: Feed
            inversedBy: subscriptions
            joinColumn:
                name: feed_id
                referencedColumnName: id
        user:
            targetEntity: User
            inversedBy: subscriptions
            joinColumn:
                name: user_id
                referencedColumnName: id
    uniqueConstraints:
        feed_user_idx:
            columns: [ feed_id, user_id ]
    lifecycleCallbacks: {  }
