MiamBundle\Entity\Tag:
    type: entity
    table: tag
    repositoryClass: MiamBundle\Repository\TagRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 50
        hash:
            type: string
            length: 40
        dateCreated:
            type: datetime
            column: date_created
    manyToMany:
        items:
            targetEntity: Item
            mappedBy: tags
    uniqueConstraints:
        hash_idx:
            columns: [ hash ]
    lifecycleCallbacks: {  }
