MiamBundle\Entity\User:
    type: entity
    table: "`user`"
    repositoryClass: MiamBundle\Repository\UserRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        username:
            type: string
            length: 255
        password:
            type: string
        salt:
            type: string
        dateCreated:
            type: datetime
            column: date_created
        dateLogin:
            type: datetime
            column: date_login
            nullable: true
        isAdmin:
            type: boolean
            column: is_admin
        isPublic:
            type: boolean
            column: is_public
        settings:
            type: text
    oneToMany:
        categories:
            targetEntity: Category
            mappedBy: user
        subscriptions:
            targetEntity: Subscription
            mappedBy: user
    lifecycleCallbacks: {  }
