<?php

namespace MiamBundle\Repository;

/**
 * EnclosureRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EnclosureRepository extends \Doctrine\ORM\EntityRepository
{
}
