<?php

namespace MiamBundle\Repository;

/**
 * FeedMarkRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FeedMarkRepository extends \Doctrine\ORM\EntityRepository
{
}
